# Generated by Django 3.0.2 on 2020-06-13 22:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='courtBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('TN', 'Tennis'), ('SQ', 'Squash'), ('BP', 'Badminton / Pickleball'), ('PT', 'Platform Tennis')], max_length=2)),
                ('courtDate', models.DateField(default=datetime.datetime(2020, 6, 13, 22, 14, 36, 806310))),
                ('courtTime', models.CharField(choices=[('5:40 AM', '5:40 AM'), ('6:00 AM', '6:00 AM'), ('6:20 AM', '6:20 AM'), ('7:00 AM', '7:00 AM'), ('7:40 AM', '7:40 AM'), ('8:00 AM', '8:00 AM'), ('8:20 AM', '8:20 AM'), ('9:00 AM', '9:00 AM'), ('9:40 AM', '9:40 AM'), ('10:00 AM', '10:00 AM'), ('10:20 AM', '10:20 AM'), ('11:00 AM', '11:00 AM'), ('11:40 AM', '11:40 AM'), ('12:00 PM', '12:00 PM'), ('12:15 PM', '12:15 PM'), ('12:20 PM', '12:20 PM'), ('1:00 PM', '1:00 PM'), ('1:15 PM', '1:15 PM'), ('1:40 PM', '1:40 PM'), ('2:00 PM', '2:00 PM'), ('2:15 PM', '2:15 PM'), ('2:20 PM', '2:20 PM'), ('3:00 PM', '3:00 PM'), ('3:30 PM', '3:30 PM'), ('3:40 PM', '3:40 PM'), ('4:00 PM', '4:00 PM'), ('4:20 PM', '4:20 PM'), ('4:30 PM', '4:30 PM'), ('5:00 PM', '5:00 PM'), ('5:30 PM', '5:30 PM'), ('5:40 PM', '5:40 PM'), ('6:00 PM', '6:00 PM'), ('6:20 PM', '6:20 PM'), ('6:30 PM', '6:30 PM'), ('7:00 PM', '7:00 PM'), ('7:30 PM', '7:30 PM'), ('7:40 PM', '7:40 PM'), ('8:00 PM', '8:00 PM'), ('8:20 PM', '8:20 PM'), ('8:30 PM', '8:30 PM'), ('9:00 PM', '9:00 PM'), ('9:30 PM', '9:30 PM'), ('9:40 PM', '9:40 PM')], max_length=8)),
                ('courtLocation', models.CharField(choices=[('B&R', 'B&R'), ('UCC', 'UCC')], max_length=3)),
                ('courtNumber', models.CharField(choices=[('1', 'Court 1'), ('2', 'Court 2'), ('3', 'Court 3'), ('4', 'Court 4')], max_length=1)),
                ('courtPlay', models.CharField(choices=[('SN', 'Singles'), ('DB', 'Doubles')], max_length=2)),
                ('comments', models.TextField(max_length=200)),
                ('player1', models.ManyToManyField(related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ManyToManyField(related_name='player2', to=settings.AUTH_USER_MODEL)),
                ('player3', models.ManyToManyField(related_name='player3', to=settings.AUTH_USER_MODEL)),
                ('player4', models.ManyToManyField(related_name='player4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
