# Generated by Django 3.0.2 on 2020-06-17 22:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtbooking',
            name='courtDate',
            field=models.DateField(default=datetime.datetime(2020, 6, 17, 22, 41, 56, 851616)),
        ),
        migrations.AlterField(
            model_name='courtbooking',
            name='player3',
            field=models.ManyToManyField(blank=True, null=True, related_name='player3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courtbooking',
            name='player4',
            field=models.ManyToManyField(blank=True, null=True, related_name='player4', to=settings.AUTH_USER_MODEL),
        ),
    ]
