# Generated by Django 3.0.2 on 2020-06-17 22:47

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0005_auto_20200617_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtbooking',
            name='courtDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='courtbooking',
            name='player3',
            field=models.ManyToManyField(blank=True, related_name='player3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courtbooking',
            name='player4',
            field=models.ManyToManyField(blank=True, related_name='player4', to=settings.AUTH_USER_MODEL),
        ),
    ]
