# Generated by Django 3.0.2 on 2020-05-10 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberLink', models.CharField(max_length=20)),
                ('memberLevel', models.CharField(max_length=20)),
                ('memberBegins', models.DateTimeField()),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('ML', 'Male'), ('FL', 'Female'), ('OT', 'Other')], max_length=2)),
                ('birthDate', models.DateField()),
                ('emailAddress', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('province', models.CharField(max_length=40)),
                ('postalCode', models.CharField(max_length=7)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('homePhone', models.CharField(max_length=14)),
                ('cellPhone', models.CharField(max_length=14)),
                ('workPhone', models.CharField(max_length=14)),
                ('tennisRank', models.DecimalField(decimal_places=2, max_digits=3)),
                ('squashRank', models.DecimalField(decimal_places=2, max_digits=3)),
                ('badmintonRank', models.DecimalField(decimal_places=2, max_digits=3)),
                ('platformRank', models.DecimalField(decimal_places=2, max_digits=3)),
                ('memberNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
