# Generated by Django 3.0.2 on 2020-06-04 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200603_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='memberBegins',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 20, 27, 55, 853646)),
        ),
    ]
