# Generated by Django 3.0.2 on 2020-06-13 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200604_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='badmintonRank',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='members',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2020, 6, 13, 22, 14, 36, 869467)),
        ),
        migrations.AlterField(
            model_name='members',
            name='memberBegins',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 22, 14, 36, 869420)),
        ),
        migrations.AlterField(
            model_name='members',
            name='platformRank',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='members',
            name='squashRank',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='members',
            name='tennisRank',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
