# Generated by Django 3.0.2 on 2020-06-17 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200613_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2020, 6, 17, 22, 41, 56, 913393)),
        ),
        migrations.AlterField(
            model_name='members',
            name='memberBegins',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 22, 41, 56, 913346)),
        ),
    ]
