# Generated by Django 3.0.2 on 2020-06-17 22:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200617_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2020, 6, 17, 22, 46, 31, 432847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='members',
            name='memberBegins',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 22, 46, 31, 432797, tzinfo=utc)),
        ),
    ]
