# Generated by Django 3.0.2 on 2020-06-17 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20200617_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='birthDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='members',
            name='memberBegins',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
